version: '3'
services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=root
    ports:
      - '5432:5432'
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
  server:
    image: 'haoyudong/todolist_server:latest'
    depends_on:
      - postgres
    ports:
      - '5001:5001'
  client:
    image: 'haoyudong/todolist_client:latest'
    ports:
      - '80:80'
    depends_on:
      - server
